sequenceDiagram
  Actor Customer as Partner
  participant Login
  participant GetBooking as Order Retrieve
  participant Reshop as Order Reshop
  participant Cancel as Order Change

  opt Authentication
    Customer ->>+ Login: LoginRQ
    Login ->> Login: Authenticating
    Login ->> Customer: LoginRS (AuthToken) + Set-Cookie (JSESSIONID + ROUTE_ID)
  end

  opt GetBooking
    Customer ->>+ GetBooking: OrderRetrieveRQ with AuthToken + Cookie (JSESSIONID + ROUTE_ID)
    GetBooking ->> GetBooking: Retrieve the order
    GetBooking ->> Customer: OrderRetrieveRS
    Customer ->>+ Reshop: OrderReshopRQ with AuthToken + Cookie (JSESSIONID + ROUTE_ID)
    Reshop ->> Reshop: Retrieve refund fees if applicable
    Reshop ->> Customer: OrderReshopRS
  end

  opt Cancel
    Customer ->>+ Cancel: OrderChangeRQ with AuthToken + Cookie (JSESSIONID + ROUTE_ID)
    Cancel ->> Cancel: Cancel the order
    Cancel ->> Customer: OrderViewRS
  end